export enum EnumBiometryStatus {
  PENDING = "PENDING",
  CAPTURE = "CAPTURE",
  STORED_DOCUMENTS = "STORED_DOCUMENTS",
  SENT_DOCUMENTS = "SENT_DOCUMENTS",
  MEDIATION = "MEDIATION",
  APPROVED = "APPROVED",
  REFUSED = "REFUSED",
  ERROR = "ERROR",
}
