export enum EnumVerificationStatus {
  PENDING_DATA = "PENDING_DATA",
  VERIFIED_DATA = "VERIFIED_DATA",
  BIOMETRY_PENDING = "BIOMETRY_PENDING",
  BIOMETRY_UNDER_ANALYSIS = "BIOMETRY_UNDER_ANALYSIS",
  BIOMETRY_REFUSED = "BIOMETRY_REFUSED",
  BIOMETRY_APPROVED = "BIOMETRY_APPROVED",
}
