export const ddi_phone = [
  { label: 'Afghanistan', value: '93', code: 'AF', flag: '🇦🇫', mask: '' },
  { label: 'Aland Islands', value: '358', code: 'AX', flag: '🇦🇽', mask: '' },
  { label: 'Albania', value: '355', code: 'AL', flag: '🇦🇱', mask: '' },
  { label: 'Algeria', value: '213', code: 'DZ', flag: '🇩🇿', mask: '' },
  { label: 'AmericanSamoa', value: '1684', code: 'AS', flag: '🇦🇸', mask: '' },
  { label: 'Andorra', value: '376', code: 'AD', flag: '🇦🇩', mask: '' },
  { label: 'Angola', value: '244', code: 'AO', flag: '🇦🇴', mask: '' },
  { label: 'Anguilla', value: '1264', code: 'AI', flag: '🇦🇮', mask: '' },
  { label: 'Antarctica', value: '672', code: 'AQ', flag: '🇦🇶', mask: '' },
  {
    label: 'Antigua and Barbuda',
    value: '1268',
    code: 'AG',
    flag: '🇦🇬',
    mask: '',
  },
  {
    label: 'Argentina',
    value: '54',
    code: 'AR',
    flag: '🇦🇷',
    mask: '(99) 99999999',
  },
  {
    label: 'Armenia',
    value: '374',
    code: 'AM',
    flag: '🇦🇲',
    mask: '99 9999999',
  },
  { label: 'Aruba', value: '297', code: 'AW', flag: '🇦🇼', mask: '' },
  {
    label: 'Australia',
    value: '61',
    code: 'AU',
    flag: '🇦🇺',
    mask: '(99) 9999 9999',
  },
  { label: 'Austria', value: '43', code: 'AT', flag: '🇦🇹', mask: '' },
  {
    label: 'Azerbaijan',
    value: '994',
    code: 'AZ',
    flag: '🇦🇿',
    mask: '(99) 999 99 99',
  },
  { label: 'Bahamas', value: '1242', code: 'BS', flag: '🇧🇸', mask: '' },
  { label: 'Bahrain', value: '973', code: 'BH', flag: '🇧🇭', mask: '' },
  { label: 'Bangladesh', value: '880', code: 'BD', flag: '🇧🇩', mask: '' },
  { label: 'Barbados', value: '1246', code: 'BB', flag: '🇧🇧', mask: '' },
  {
    label: 'Belarus',
    value: '375',
    code: 'BY',
    flag: '🇧🇾',
    mask: '(99) 999 99 99',
  },
  {
    label: 'Belgium',
    value: '32',
    code: 'BE',
    flag: '🇧🇪',
    mask: '999 99 99 99',
  },
  { label: 'Belize', value: '501', code: 'BZ', flag: '🇧🇿', mask: '' },
  { label: 'Benin', value: '229', code: 'BJ', flag: '🇧🇯', mask: '' },
  { label: 'Bermuda', value: '1441', code: 'BM', flag: '🇧🇲', mask: '' },
  { label: 'Bhutan', value: '975', code: 'BT', flag: '🇧🇹', mask: '' },
  {
    label: 'Bolivia, Plurinational State of',
    value: '591',
    code: 'BO',
    flag: '🇧🇴',
    mask: '',
  },
  {
    label: 'Bosnia and Herzegovina',
    value: '387',
    code: 'BA',
    flag: '🇧🇦',
    mask: '',
  },
  { label: 'Botswana', value: '267', code: 'BW', flag: '🇧🇼', mask: '' },
  {
    label: 'Brazil',
    value: '55',
    code: 'BR',
    flag: '🇧🇷',
    mask: '(99) 99999-9999',
  },
  {
    label: 'British Indian Ocean Territory',
    value: '246',
    code: 'IO',
    flag: '🇮🇴',
    mask: '',
  },
  {
    label: 'Brunei Darussalam',
    value: '673',
    code: 'BN',
    flag: '🇧🇳',
    mask: '',
  },
  { label: 'Bulgaria', value: '359', code: 'BG', flag: '🇧🇬', mask: '' },
  { label: 'Burkina Faso', value: '226', code: 'BF', flag: '🇧🇫', mask: '' },
  { label: 'Burundi', value: '257', code: 'BI', flag: '🇧🇮', mask: '' },
  { label: 'Cambodia', value: '855', code: 'KH', flag: '🇰🇭', mask: '' },
  { label: 'Cameroon', value: '237', code: 'CM', flag: '🇨🇲', mask: '' },
  {
    label: 'Canada',
    value: '1',
    code: 'CA',
    flag: '🇨🇦',
    mask: '(999) 999-9999',
  },
  { label: 'Cape Verde', value: '238', code: 'CV', flag: '🇨🇻', mask: '' },
  {
    label: 'Cayman Islands',
    value: ' 345',
    code: 'KY',
    flag: '🇰🇾',
    mask: '',
  },
  {
    label: 'Central African Republic',
    value: '236',
    code: 'CF',
    flag: '🇨🇫',
    mask: '',
  },
  { label: 'Chad', value: '235', code: 'TD', flag: '🇹🇩', mask: '' },
  { label: 'Chile', value: '56', code: 'CL', flag: '🇨🇱', mask: '' },
  {
    label: 'China',
    value: '86',
    code: 'CN',
    flag: '🇨🇳',
    mask: '99-999999999',
  },
  {
    label: 'Christmas Island',
    value: '61',
    code: 'CX',
    flag: '🇨🇽',
    mask: '',
  },
  {
    label: 'Cocos (Keeling) Islands',
    value: '61',
    code: 'CC',
    flag: '🇨🇨',
    mask: '',
  },
  {
    label: 'Colombia',
    value: '57',
    code: 'CO',
    flag: '🇨🇴',
    mask: '999 999 9999',
  },
  { label: 'Comoros', value: '269', code: 'KM', flag: '🇰🇲', mask: '' },
  { label: 'Congo', value: '242', code: 'CG', flag: '🇨🇬', mask: '' },
  {
    label: 'Congo, The Democratic Republic of the Congo',
    value: '243',
    code: 'CD',
    flag: '🇨🇩',
    mask: '',
  },
  { label: 'Cook Islands', value: '682', code: 'CK', flag: '🇨🇰', mask: '' },
  {
    label: 'Costa Rica',
    value: '506',
    code: 'CR',
    flag: '🇨🇷',
    mask: '9999-9999',
  },
  {
    label: "Cote d'Ivoire",
    value: '225',
    code: 'CI',
    flag: '🇨🇮',
    mask: '99 99 99 99',
  },
  { label: 'Croatia', value: '385', code: 'HR', flag: '🇭🇷', mask: '' },
  { label: 'Cuba', value: '53', code: 'CU', flag: '🇨🇺', mask: '' },
  {
    label: 'Cyprus',
    value: '357',
    code: 'CY',
    flag: '🇨🇾',
    mask: '99 999999',
  },
  { label: 'Czech Republic', value: '420', code: 'CZ', flag: '🇨🇿', mask: '' },
  {
    label: 'Denmark',
    value: '45',
    code: 'DK',
    flag: '🇩🇰',
    mask: '99 99 99 99',
  },
  { label: 'Djibouti', value: '253', code: 'DJ', flag: '🇩🇯', mask: '' },
  { label: 'Dominica', value: '1767', code: 'DM', flag: '🇩🇲', mask: '' },
  {
    label: 'Dominican Republic',
    value: '1849',
    code: 'DO',
    flag: '🇩🇴',
    mask: '',
  },
  { label: 'Ecuador', value: '593', code: 'EC', flag: '🇪🇨', mask: '' },
  { label: 'Egypt', value: '20', code: 'EG', flag: '🇪🇬', mask: '' },
  {
    label: 'El Salvador',
    value: '503',
    code: 'SV',
    flag: '🇸🇻',
    mask: '9999-9999',
  },
  {
    label: 'Equatorial Guinea',
    value: '240',
    code: 'GQ',
    flag: '🇬🇶',
    mask: '',
  },
  { label: 'Eritrea', value: '291', code: 'ER', flag: '🇪🇷', mask: '' },
  {
    label: 'Estonia',
    value: '372',
    code: 'EE',
    flag: '🇪🇪',
    mask: '9999 999999',
  },
  { label: 'Ethiopia', value: '251', code: 'ET', flag: '🇪🇹', mask: '' },
  {
    label: 'Falkland Islands (Malvinas)',
    value: '500',
    code: 'FK',
    flag: '🇫🇰',
    mask: '',
  },
  { label: 'Faroe Islands', value: '298', code: 'FO', flag: '🇫🇴', mask: '' },
  { label: 'Fiji', value: '679', code: 'FJ', flag: '🇫🇯', mask: '' },
  {
    label: 'Finland',
    value: '358',
    code: 'FI',
    flag: '🇫🇮',
    mask: '9 99 99 99 99',
  },
  { label: 'France', value: '33', code: 'FR', flag: '🇫🇷', mask: '' },
  { label: 'French Guiana', value: '594', code: 'GF', flag: '🇬🇫', mask: '' },
  {
    label: 'French Polynesia',
    value: '689',
    code: 'PF',
    flag: '🇵🇫',
    mask: '',
  },
  { label: 'Gabon', value: '241', code: 'GA', flag: '🇬🇦', mask: '' },
  { label: 'Gambia', value: '220', code: 'GM', flag: '🇬🇲', mask: '' },
  { label: 'Georgia', value: '995', code: 'GE', flag: '🇬🇪', mask: '' },
  {
    label: 'Germany',
    value: '49',
    code: 'DE',
    flag: '🇩🇪',
    mask: '9999 99999999',
  },
  { label: 'Ghana', value: '233', code: 'GH', flag: '🇬🇭', mask: '' },
  { label: 'Gibraltar', value: '350', code: 'GI', flag: '🇬🇮', mask: '' },
  { label: 'Greece', value: '30', code: 'GR', flag: '🇬🇷', mask: '' },
  { label: 'Greenland', value: '299', code: 'GL', flag: '🇬🇱', mask: '' },
  { label: 'Grenada', value: '1473', code: 'GD', flag: '🇬🇩', mask: '' },
  { label: 'Guadeloupe', value: '590', code: 'GP', flag: '🇬🇵', mask: '' },
  { label: 'Guam', value: '1671', code: 'GU', flag: '🇬🇺', mask: '' },
  {
    label: 'Guatemala',
    value: '502',
    code: 'GT',
    flag: '🇬🇹',
    mask: '9999-9999',
  },
  { label: 'Guernsey', value: '44', code: 'GG', flag: '🇬🇬', mask: '' },
  { label: 'Guinea', value: '224', code: 'GN', flag: '🇬🇳', mask: '' },
  { label: 'Guinea-Bissau', value: '245', code: 'GW', flag: '🇬🇼', mask: '' },
  { label: 'Guyana', value: '595', code: 'GY', flag: '🇬🇾', mask: '' },
  { label: 'Haiti', value: '509', code: 'HT', flag: '🇭🇹', mask: '9999-9999' },
  {
    label: 'Holy See (Vatican City State)',
    value: '379',
    code: 'VA',
    flag: '🇻🇦',
    mask: '',
  },
  { label: 'Honduras', value: '504', code: 'HN', flag: '🇭🇳', mask: '' },
  {
    label: 'Hong Kong',
    value: '852',
    code: 'HK',
    flag: '🇭🇰',
    mask: '9999 9999',
  },
  { label: 'Hungary', value: '36', code: 'HU', flag: '🇭🇺', mask: '' },
  {
    label: 'Iceland',
    value: '354',
    code: 'IS',
    flag: '🇮🇸',
    mask: '999 9999',
  },
  {
    label: 'India',
    value: '91',
    code: 'IN',
    flag: '🇮🇳',
    mask: '99999-99999',
  },
  { label: 'Indonesia', value: '62', code: 'ID', flag: '🇮🇩', mask: '' },
  {
    label: 'Iran, Islamic Republic of Persian Gulf',
    value: '98',
    code: 'IR',
    flag: '🇮🇷',
    mask: '999 999 9999',
  },
  { label: 'Iraq', value: '964', code: 'IQ', flag: '🇮🇶', mask: '' },
  {
    label: 'Ireland',
    value: '353',
    code: 'IE',
    flag: '🇮🇪',
    mask: '99 9999999',
  },
  { label: 'Isle of Man', value: '44', code: 'IM', flag: '🇮🇲', mask: '' },
  {
    label: 'Israel',
    value: '972',
    code: 'IL',
    flag: '🇮🇱',
    mask: '999 999 9999',
  },
  {
    label: 'Italy',
    value: '39',
    code: 'IT',
    flag: '🇮🇹',
    mask: '999 9999999',
  },
  { label: 'Jamaica', value: '1876', code: 'JM', flag: '🇯🇲', mask: '' },
  {
    label: 'Japan',
    value: '81',
    code: 'JP',
    flag: '🇯🇵',
    mask: '99 9999 9999',
  },
  { label: 'Jersey', value: '44', code: 'JE', flag: '🇯🇪', mask: '' },
  { label: 'Jordan', value: '962', code: 'JO', flag: '🇯🇴', mask: '' },
  {
    label: 'Kazakhstan',
    value: '77',
    code: 'KZ',
    flag: '🇰🇿',
    mask: '999 999-99-99',
  },
  { label: 'Kenya', value: '254', code: 'KE', flag: '🇰🇪', mask: '' },
  { label: 'Kiribati', value: '686', code: 'KI', flag: '🇰🇮', mask: '' },
  {
    label: "Korea, Democratic People's Republic of Korea",
    value: '850',
    code: 'KP',
    flag: '🇰🇵',
    mask: '',
  },
  {
    label: 'Korea, Republic of South Korea',
    value: '82',
    code: 'KR',
    flag: '🇰🇷',
    mask: '',
  },
  { label: 'Kuwait', value: '965', code: 'KW', flag: '🇰🇼', mask: '' },
  {
    label: 'Kyrgyzstan',
    value: '996',
    code: 'KG',
    flag: '🇰🇬',
    mask: '999 999 999',
  },
  { label: 'Laos', value: '856', code: 'LA', flag: '🇱🇦', mask: '' },
  {
    label: 'Latvia',
    value: '371',
    code: 'LV',
    flag: '🇱🇻',
    mask: '99 999 999',
  },
  { label: 'Lebanon', value: '961', code: 'LB', flag: '🇱🇧', mask: '' },
  { label: 'Lesotho', value: '266', code: 'LS', flag: '🇱🇸', mask: '' },
  { label: 'Liberia', value: '231', code: 'LR', flag: '🇱🇷', mask: '' },
  {
    label: 'Libyan Arab Jamahiriya',
    value: '218',
    code: 'LY',
    flag: '🇱🇾',
    mask: '',
  },
  { label: 'Liechtenstein', value: '423', code: 'LI', flag: '🇱🇮', mask: '' },
  { label: 'Lithuania', value: '370', code: 'LT', flag: '🇱🇹', mask: '' },
  { label: 'Luxembourg', value: '352', code: 'LU', flag: '🇱🇺', mask: '' },
  { label: 'Macao', value: '853', code: 'MO', flag: '🇲🇴', mask: '' },
  { label: 'Macedonia', value: '389', code: 'MK', flag: '🇲🇰', mask: '' },
  { label: 'Madagascar', value: '261', code: 'MG', flag: '🇲🇬', mask: '' },
  { label: 'Malawi', value: '265', code: 'MW', flag: '🇲🇼', mask: '' },
  {
    label: 'Malaysia',
    value: '60',
    code: 'MY',
    flag: '🇲🇾',
    mask: '99-9999-9999',
  },
  { label: 'Maldives', value: '960', code: 'MV', flag: '🇲🇻', mask: '' },
  { label: 'Mali', value: '223', code: 'ML', flag: '🇲🇱', mask: '' },
  { label: 'Malta', value: '356', code: 'MT', flag: '🇲🇹', mask: '' },
  {
    label: 'Marshall Islands',
    value: '692',
    code: 'MH',
    flag: '🇲🇭',
    mask: '',
  },
  { label: 'Martinique', value: '596', code: 'MQ', flag: '🇲🇶', mask: '' },
  { label: 'Mauritania', value: '222', code: 'MR', flag: '🇲🇷', mask: '' },
  { label: 'Mauritius', value: '230', code: 'MU', flag: '🇲🇺', mask: '' },
  { label: 'Mayotte', value: '262', code: 'YT', flag: '🇾🇹', mask: '' },
  {
    label: 'Mexico',
    value: '52',
    code: 'MX',
    flag: '🇲🇽',
    mask: '999 999 9999',
  },
  {
    label: 'Micronesia, Federated States of Micronesia',
    value: '691',
    code: 'FM',
    flag: '🇫🇲',
    mask: '',
  },
  {
    label: 'Moldova',
    value: '373',
    code: 'MD',
    flag: '🇲🇩',
    mask: '(99) 99-99-99',
  },
  { label: 'Monaco', value: '377', code: 'MC', flag: '🇲🇨', mask: '' },
  { label: 'Mongolia', value: '976', code: 'MN', flag: '🇲🇳', mask: '' },
  { label: 'Montenegro', value: '382', code: 'ME', flag: '🇲🇪', mask: '' },
  { label: 'Montserrat', value: '1664', code: 'MS', flag: '🇲🇸', mask: '' },
  { label: 'Morocco', value: '212', code: 'MA', flag: '🇲🇦', mask: '' },
  { label: 'Mozambique', value: '258', code: 'MZ', flag: '🇲🇿', mask: '' },
  { label: 'Myanmar', value: '95', code: 'MM', flag: '🇲🇲', mask: '' },
  { label: 'Namibia', value: '264', code: 'NA', flag: '🇳🇦', mask: '' },
  { label: 'Nauru', value: '674', code: 'NR', flag: '🇳🇷', mask: '' },
  { label: 'Nepal', value: '977', code: 'NP', flag: '🇳🇵', mask: '' },
  {
    label: 'Netherlands',
    value: '31',
    code: 'NL',
    flag: '🇳🇱',
    mask: '99 99999999',
  },
  { label: 'New Caledonia', value: '687', code: 'NC', flag: '🇳🇨', mask: '' },
  {
    label: 'New Zealand',
    value: '64',
    code: 'NZ',
    flag: '🇳🇿',
    mask: '999-999-9999',
  },
  { label: 'Nicaragua', value: '505', code: 'NI', flag: '🇳🇮', mask: '' },
  { label: 'Niger', value: '227', code: 'NE', flag: '🇳🇪', mask: '' },
  { label: 'Nigeria', value: '234', code: 'NG', flag: '🇳🇬', mask: '' },
  { label: 'Niue', value: '683', code: 'NU', flag: '🇳🇺', mask: '' },
  { label: 'Norfolk Island', value: '672', code: 'NF', flag: '🇳🇫', mask: '' },
  {
    label: 'Northern Mariana Islands',
    value: '1670',
    code: 'MP',
    flag: '🇲🇵',
    mask: '',
  },
  {
    label: 'Norway',
    value: '47',
    code: 'NO',
    flag: '🇳🇴',
    mask: '999 99 999',
  },
  { label: 'Oman', value: '968', code: 'OM', flag: '🇴🇲', mask: '' },
  {
    label: 'Pakistan',
    value: '92',
    code: 'PK',
    flag: '🇵🇰',
    mask: '999-9999999',
  },
  { label: 'Palau', value: '680', code: 'PW', flag: '🇵🇼', mask: '' },
  {
    label: 'Palestinian Territory, Occupied',
    value: '970',
    code: 'PS',
    flag: '🇵🇸',
    mask: '',
  },
  { label: 'Panama', value: '507', code: 'PA', flag: '🇵🇦', mask: '' },
  {
    label: 'Papua New Guinea',
    value: '675',
    code: 'PG',
    flag: '🇵🇬',
    mask: '',
  },
  { label: 'Paraguay', value: '595', code: 'PY', flag: '🇵🇾', mask: '' },
  { label: 'Peru', value: '51', code: 'PE', flag: '🇵🇪', mask: '' },
  {
    label: 'Philippines',
    value: '63',
    code: 'PH',
    flag: '🇵🇭',
    mask: '9999 9999999',
  },
  { label: 'Pitcairn', value: '872', code: 'PN', flag: '🇵🇳', mask: '' },
  {
    label: 'Poland',
    value: '48',
    code: 'PL',
    flag: '🇵🇱',
    mask: '999-999-999',
  },
  { label: 'Portugal', value: '351', code: 'PT', flag: '🇵🇹', mask: '' },
  { label: 'Puerto Rico', value: '1939', code: 'PR', flag: '🇵🇷', mask: '' },
  { label: 'Qatar', value: '974', code: 'QA', flag: '🇶🇦', mask: '' },
  { label: 'Romania', value: '40', code: 'RO', flag: '🇷🇴', mask: '' },
  {
    label: 'Russia',
    value: '7',
    code: 'RU',
    flag: '🇷🇺',
    mask: '(999) 999-99-99',
  },
  { label: 'Rwanda', value: '250', code: 'RW', flag: '🇷🇼', mask: '' },
  { label: 'Reunion', value: '262', code: 'RE', flag: '🇷🇪', mask: '' },
  {
    label: 'Saint Barthelemy',
    value: '590',
    code: 'BL',
    flag: '🇧🇱',
    mask: '',
  },
  {
    label: 'Saint Helena, Ascension and Tristan Da Cunha',
    value: '290',
    code: 'SH',
    flag: '🇸🇭',
    mask: '',
  },
  {
    label: 'Saint Kitts and Nevis',
    value: '1869',
    code: 'KN',
    flag: '🇰🇳',
    mask: '',
  },
  { label: 'Saint Lucia', value: '1758', code: 'LC', flag: '🇱🇨', mask: '' },
  { label: 'Saint Martin', value: '590', code: 'MF', flag: '🇲🇫', mask: '' },
  {
    label: 'Saint Pierre and Miquelon',
    value: '508',
    code: 'PM',
    flag: '🇵🇲',
    mask: '',
  },
  {
    label: 'Saint Vincent and the Grenadines',
    value: '1784',
    code: 'VC',
    flag: '🇻🇨',
    mask: '',
  },
  { label: 'Samoa', value: '685', code: 'WS', flag: '🇼🇸', mask: '' },
  { label: 'San Marino', value: '378', code: 'SM', flag: '🇸🇲', mask: '' },
  {
    label: 'Sao Tome and Principe',
    value: '239',
    code: 'ST',
    flag: '🇸🇹',
    mask: '',
  },
  { label: 'Saudi Arabia', value: '966', code: 'SA', flag: '🇸🇦', mask: '' },
  { label: 'Senegal', value: '221', code: 'SN', flag: '🇸🇳', mask: '' },
  { label: 'Serbia', value: '381', code: 'RS', flag: '🇷🇸', mask: '' },
  { label: 'Seychelles', value: '248', code: 'SC', flag: '🇸🇨', mask: '' },
  { label: 'Sierra Leone', value: '232', code: 'SL', flag: '🇸🇱', mask: '' },
  {
    label: 'Singapore',
    value: '65',
    code: 'SG',
    flag: '🇸🇬',
    mask: '9999-9999',
  },
  { label: 'Slovakia', value: '421', code: 'SK', flag: '🇸🇰', mask: '' },
  { label: 'Slovenia', value: '386', code: 'SI', flag: '🇸🇮', mask: '' },
  {
    label: 'Solomon Islands',
    value: '677',
    code: 'SB',
    flag: '🇸🇧',
    mask: '',
  },
  { label: 'Somalia', value: '252', code: 'SO', flag: '🇸🇴', mask: '' },
  { label: 'South Africa', value: '27', code: 'ZA', flag: '🇿🇦', mask: '' },
  { label: 'South Sudan', value: '211', code: 'SS', flag: '🇸🇸', mask: '' },
  {
    label: 'South Georgia and the South Sandwich Islands',
    value: '500',
    code: 'GS',
    flag: '🇬🇸',
    mask: '',
  },
  {
    label: 'Spain',
    value: '34',
    code: 'ES',
    flag: '🇪🇸',
    mask: '999 999 999',
  },
  { label: 'Sri Lanka', value: '94', code: 'LK', flag: '🇱🇰', mask: '' },
  { label: 'Sudan', value: '249', code: 'SD', flag: '🇸🇩', mask: '' },
  { label: 'Suriname', value: '597', code: 'SR', flag: '🇸🇷', mask: '' },
  {
    label: 'Svalbard and Jan Mayen',
    value: '47',
    code: 'SJ',
    flag: '🇸🇯',
    mask: '',
  },
  { label: 'Swaziland', value: '268', code: 'SZ', flag: '🇸🇿', mask: '' },
  {
    label: 'Sweden',
    value: '46',
    code: 'SE',
    flag: '🇸🇪',
    mask: '(999) 999-999',
  },
  {
    label: 'Switzerland',
    value: '41',
    code: 'CH',
    flag: '🇨🇭',
    mask: '99 999 99 99',
  },
  {
    label: 'Syrian Arab Republic',
    value: '963',
    code: 'SY',
    flag: '🇸🇾',
    mask: '',
  },
  { label: 'Taiwan', value: '886', code: 'TW', flag: '🇹🇼', mask: '' },
  { label: 'Tajikistan', value: '992', code: 'TJ', flag: '🇹🇯', mask: '' },
  {
    label: 'Tanzania, United Republic of Tanzania',
    value: '255',
    code: 'TZ',
    flag: '🇹🇿',
    mask: '',
  },
  { label: 'Thailand', value: '66', code: 'TH', flag: '🇹🇭', mask: '' },
  { label: 'Timor-Leste', value: '670', code: 'TL', flag: '🇹🇱', mask: '' },
  { label: 'Togo', value: '228', code: 'TG', flag: '🇹🇬', mask: '' },
  { label: 'Tokelau', value: '690', code: 'TK', flag: '🇹🇰', mask: '' },
  { label: 'Tonga', value: '676', code: 'TO', flag: '🇹🇴', mask: '' },
  {
    label: 'Trinidad and Tobago',
    value: '1868',
    code: 'TT',
    flag: '🇹🇹',
    mask: '',
  },
  { label: 'Tunisia', value: '216', code: 'TN', flag: '🇹🇳', mask: '' },
  {
    label: 'Turkey',
    value: '90',
    code: 'TR',
    flag: '🇹🇷',
    mask: '999 999 99 99',
  },
  { label: 'Turkmenistan', value: '993', code: 'TM', flag: '🇹🇲', mask: '' },
  {
    label: 'Turks and Caicos Islands',
    value: '1649',
    code: 'TC',
    flag: '🇹🇨',
    mask: '',
  },
  { label: 'Tuvalu', value: '688', code: 'TV', flag: '🇹🇻', mask: '' },
  { label: 'Uganda', value: '256', code: 'UG', flag: '🇺🇬', mask: '' },
  {
    label: 'Ukraine',
    value: '380',
    code: 'UA',
    flag: '🇺🇦',
    mask: '(99) 999 99 99',
  },
  {
    label: 'United Arab Emirates',
    value: '971',
    code: 'AE',
    flag: '🇦🇪',
    mask: '',
  },
  {
    label: 'United Kingdom',
    value: '44',
    code: 'GB',
    flag: '🇬🇧',
    mask: '9999 999999',
  },
  {
    label: 'United States',
    value: '1',
    code: 'US',
    flag: '🇺🇸',
    mask: '(999) 999-9999',
  },
  { label: 'Uruguay', value: '598', code: 'UY', flag: '🇺🇾', mask: '' },
  {
    label: 'Uzbekistan',
    value: '998',
    code: 'UZ',
    flag: '🇺🇿',
    mask: '99 999 99 99',
  },
  { label: 'Vanuatu', value: '678', code: 'VU', flag: '🇻🇺', mask: '' },
  {
    label: 'Venezuela, Bolivarian Republic of Venezuela',
    value: '58',
    code: 'VE',
    flag: '🇻🇪',
    mask: '',
  },
  { label: 'Vietnam', value: '84', code: 'VN', flag: '🇻🇳', mask: '' },
  {
    label: 'Virgin Islands, British',
    value: '1284',
    code: 'VG',
    flag: '🇻🇬',
    mask: '',
  },
  {
    label: 'Virgin Islands, U.S.',
    value: '1340',
    code: 'VI',
    flag: '🇻🇮',
    mask: '',
  },
  {
    label: 'Wallis and Futuna',
    value: '681',
    code: 'WF',
    flag: '🇼🇫',
    mask: '',
  },
  { label: 'Yemen', value: '967', code: 'YE', flag: '🇾🇪', mask: '' },
  { label: 'Zambia', value: '260', code: 'ZM', flag: '🇿🇲', mask: '' },
  { label: 'Zimbabwe', value: '263', code: 'ZW', flag: '🇿🇼', mask: '' },
];
