export enum EnumStorageSignIn {
  ACCESS = '@kirvano:accessToken',
  REFRESH = '@kirvano:refreshToken',
  USER = '@kirvano:userResponse',
  USER_DATA = '@kirvano:userData',
  USER_REMEMBER = '@kirvano:userRemember',
  COMPANIES = '@kirvano:companies',
  BIOMETRY = '@kirvano:biometry',
  ONBOARDING = '@kirvano:onboarding',
  FINGERPRINT = '@kirvano:fingerprint',
  BIOMETRY_ACCEPTED = '@kirvano:biometricAccepted',
  USER_UUID = '@kirvano:userUUID',
  CHECK_PERMISSION = '@kirvano:checkPermission',
  ASKED = '@kirvano:asked',
  SHOW_SPLASH = '@kirvano:showSplash',
  USER_CONFIGURE = ' @kirvano:userConfig',
  THEME = ' @kirvano:theme',
}
